
version: '3.7'

networks:
  jenkins_network:
    external:
      name: ${PROJECT_NAME}_jenkins_network

services:
  nginx:
    build: .
    container_name: nginx_jenkins
    hostname: nginx_jenkins
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - PROJECT_DNS=${PROJECT_DNS}
    ports:
      - 80:80
      - 443:443
    command: bash -c "envsubst < /etc/nginx/conf.d/nginx_template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - jenkins_network
